### ISSUE TITLE
[ENTREGA Primer Recuperatorio Objetos] Marianela Benítez

### ISSUE THREAD

**Issue by MarianelaBen** [pdep-lunes-tarde/2024-objetos-recuperatorio-1-MarianelaBen#1]
Juan Fernandes y Lucas Zheng @juanFdS @zhl27 
Juani Schuhmann y Dante Ortiz @jschuhmann47 @Effloresc3 
Tomás Antonio @T-J-Antonio
Gustavo Crespi y Manuel Torrente @gcrespi @manutorrente

**Comment by JuanFdS** [comment]
Parte A
---

- tunicaEpica debería ser una clase, nunca menciona que sea una sola, lo mismo con los amuletos. La ojota está bien que sea una.
- En ojota se rompe el encapsulamiento con mago.nombre().size()
- Bien que se valida que `poderInnato` esté entre 1 y 10, pero debería ser al modificarlo, no al pedir el dato.
- Si no puede ganarle un mago a otro, no hace falta que tire un error.
- Entre aprendiz y veterano se puede llegar a extraer la lógica repetida usando coeficientes para multiplicar.

Parte B
---

- La validación de dos miembros debería ser antes de crear el objeto.
- Bien que gremio y mago son polimórficos.
- La energía que pierde cada uno debería dividirse por la cantidad total (o multiplicar lo que gana el líder)
- El líder es algo calculable, si se guarda es más dificil de modificar ante un cambio del estado
- El mago no tiene un líder, solo los gremios lo tienen

Nota: 8
